---
- name: Common tasks FTW
  hosts: all
  become: yes
  pre_tasks:
    - name: Set hostname
      hostname: name={{inventory_hostname}}

- name: Base bamboo service
  hosts: myd-vm06383.hpeswlab.net
  become: yes
  roles:
    - { role: img-panda, tags: img-panda }
    - { role: smart-panda, tags: smart-panda }
    
