---
- name: copy smart-panda app
  copy: src=smart-panda dest=/tmp/ owner=root group=root mode=0755

- name: npm install
  npm: path=/tmp/smart-panda

- name: Stop APP
  command: pm2 stop smart-panda
  args:
    chdir: /tmp/smart-panda
  ignore_errors: yes

    
- name: Start APP
  command: pm2 start smart-panda.js --name smart-panda
  args:
    chdir: /tmp/smart-panda
